/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "cot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cot_PointA, cot_PointA, AUTO)


PB_BIND(cot_PointB, cot_PointB, AUTO)


PB_BIND(cot_EncryptedPayloads, cot_EncryptedPayloads, AUTO)



