// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cot.proto
// Protobuf C++ Version: 7.34.1

#ifndef cot_2eproto_2epb_2eh
#define cot_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cot_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cot_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cot_2eproto;
}  // extern "C"
namespace cot {
class EncryptedPayloads;
struct EncryptedPayloadsDefaultTypeInternal;
extern EncryptedPayloadsDefaultTypeInternal _EncryptedPayloads_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EncryptedPayloads_class_data_;
class PointA;
struct PointADefaultTypeInternal;
extern PointADefaultTypeInternal _PointA_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PointA_class_data_;
class PointB;
struct PointBDefaultTypeInternal;
extern PointBDefaultTypeInternal _PointB_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PointB_class_data_;
}  // namespace cot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cot {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PointB final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cot.PointB) */ {
 public:
  inline PointB() : PointB(nullptr) {}
  ~PointB() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PointB* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PointB));
  }
#endif

  template <typename = void>
  explicit constexpr PointB(::google::protobuf::internal::ConstantInitialized);

  inline PointB(const PointB& from) : PointB(nullptr, from) {}
  inline PointB(PointB&& from) noexcept
      : PointB(nullptr, ::std::move(from)) {}
  inline PointB& operator=(const PointB& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointB& operator=(PointB&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PointB& default_instance() {
    return *reinterpret_cast<const PointB*>(
        &_PointB_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PointB& a, PointB& b) { a.Swap(&b); }
  inline void Swap(PointB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointB* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PointB* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PointB>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PointB& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PointB& from) { PointB::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PointB* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cot.PointB"; }

  explicit PointB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PointB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PointB& from);
  PointB(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PointB&& from) noexcept
      : PointB(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // bytes x = 1;
  void clear_x() ;
  [[nodiscard]] const ::std::string& x() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_x(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_x();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_x();
  void set_allocated_x(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_x() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_x(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_x();

  public:
  // bytes y = 2;
  void clear_y() ;
  [[nodiscard]] const ::std::string& y() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_y(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_y();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_y();
  void set_allocated_y(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_y() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_y(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_y();

  public:
  // @@protoc_insertion_point(class_scope:cot.PointB)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PointB& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr x_;
    ::google::protobuf::internal::ArenaStringPtr y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cot_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PointB_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PointA final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cot.PointA) */ {
 public:
  inline PointA() : PointA(nullptr) {}
  ~PointA() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PointA* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PointA));
  }
#endif

  template <typename = void>
  explicit constexpr PointA(::google::protobuf::internal::ConstantInitialized);

  inline PointA(const PointA& from) : PointA(nullptr, from) {}
  inline PointA(PointA&& from) noexcept
      : PointA(nullptr, ::std::move(from)) {}
  inline PointA& operator=(const PointA& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointA& operator=(PointA&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PointA& default_instance() {
    return *reinterpret_cast<const PointA*>(
        &_PointA_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PointA& a, PointA& b) { a.Swap(&b); }
  inline void Swap(PointA* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointA* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PointA* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PointA>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PointA& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PointA& from) { PointA::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PointA* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cot.PointA"; }

  explicit PointA(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PointA(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PointA& from);
  PointA(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PointA&& from) noexcept
      : PointA(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // bytes x = 1;
  void clear_x() ;
  [[nodiscard]] const ::std::string& x() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_x(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_x();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_x();
  void set_allocated_x(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_x() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_x(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_x();

  public:
  // bytes y = 2;
  void clear_y() ;
  [[nodiscard]] const ::std::string& y() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_y(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_y();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_y();
  void set_allocated_y(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_y() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_y(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_y();

  public:
  // @@protoc_insertion_point(class_scope:cot.PointA)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PointA& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr x_;
    ::google::protobuf::internal::ArenaStringPtr y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cot_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PointA_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED EncryptedPayloads final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cot.EncryptedPayloads) */ {
 public:
  inline EncryptedPayloads() : EncryptedPayloads(nullptr) {}
  ~EncryptedPayloads() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EncryptedPayloads* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EncryptedPayloads));
  }
#endif

  template <typename = void>
  explicit constexpr EncryptedPayloads(::google::protobuf::internal::ConstantInitialized);

  inline EncryptedPayloads(const EncryptedPayloads& from) : EncryptedPayloads(nullptr, from) {}
  inline EncryptedPayloads(EncryptedPayloads&& from) noexcept
      : EncryptedPayloads(nullptr, ::std::move(from)) {}
  inline EncryptedPayloads& operator=(const EncryptedPayloads& from) {
    CopyFrom(from);
    return *this;
  }
  inline EncryptedPayloads& operator=(EncryptedPayloads&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const EncryptedPayloads& default_instance() {
    return *reinterpret_cast<const EncryptedPayloads*>(
        &_EncryptedPayloads_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(EncryptedPayloads& a, EncryptedPayloads& b) { a.Swap(&b); }
  inline void Swap(EncryptedPayloads* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EncryptedPayloads* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] EncryptedPayloads* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EncryptedPayloads>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EncryptedPayloads& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EncryptedPayloads& from) { EncryptedPayloads::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EncryptedPayloads* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cot.EncryptedPayloads"; }

  explicit EncryptedPayloads(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EncryptedPayloads(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EncryptedPayloads& from);
  EncryptedPayloads(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EncryptedPayloads&& from) noexcept
      : EncryptedPayloads(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kE0FieldNumber = 1,
    kE1FieldNumber = 2,
  };
  // bytes e0 = 1;
  void clear_e0() ;
  [[nodiscard]] const ::std::string& e0() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_e0(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_e0();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_e0();
  void set_allocated_e0(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_e0() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_e0(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_e0();

  public:
  // bytes e1 = 2;
  void clear_e1() ;
  [[nodiscard]] const ::std::string& e1() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_e1(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_e1();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_e1();
  void set_allocated_e1(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_e1() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_e1(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_e1();

  public:
  // @@protoc_insertion_point(class_scope:cot.EncryptedPayloads)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EncryptedPayloads& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr e0_;
    ::google::protobuf::internal::ArenaStringPtr e1_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cot_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EncryptedPayloads_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PointA

// bytes x = 1;
inline void PointA::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PointA::x() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.PointA.x)
  return _internal_x();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PointA::set_x(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.x_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.PointA.x)
}
inline ::std::string* PROTOBUF_NONNULL PointA::mutable_x()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_x();
  // @@protoc_insertion_point(field_mutable:cot.PointA.x)
  return _s;
}
inline const ::std::string& PointA::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_.Get();
}
inline void PointA::_internal_set_x(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PointA::_internal_mutable_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.x_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PointA::release_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.PointA.x)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.x_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.x_.Set("", GetArena());
  }
  return released;
}
inline void PointA::set_allocated_x(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.x_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.x_.IsDefault()) {
    _impl_.x_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.PointA.x)
}

// bytes y = 2;
inline void PointA::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PointA::y() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.PointA.y)
  return _internal_y();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PointA::set_y(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.y_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.PointA.y)
}
inline ::std::string* PROTOBUF_NONNULL PointA::mutable_y()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_y();
  // @@protoc_insertion_point(field_mutable:cot.PointA.y)
  return _s;
}
inline const ::std::string& PointA::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_.Get();
}
inline void PointA::_internal_set_y(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PointA::_internal_mutable_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.y_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PointA::release_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.PointA.y)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.y_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.y_.Set("", GetArena());
  }
  return released;
}
inline void PointA::set_allocated_y(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.y_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.y_.IsDefault()) {
    _impl_.y_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.PointA.y)
}

// -------------------------------------------------------------------

// PointB

// bytes x = 1;
inline void PointB::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& PointB::x() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.PointB.x)
  return _internal_x();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PointB::set_x(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.x_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.PointB.x)
}
inline ::std::string* PROTOBUF_NONNULL PointB::mutable_x()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_x();
  // @@protoc_insertion_point(field_mutable:cot.PointB.x)
  return _s;
}
inline const ::std::string& PointB::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_.Get();
}
inline void PointB::_internal_set_x(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PointB::_internal_mutable_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.x_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PointB::release_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.PointB.x)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.x_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.x_.Set("", GetArena());
  }
  return released;
}
inline void PointB::set_allocated_x(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.x_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.x_.IsDefault()) {
    _impl_.x_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.PointB.x)
}

// bytes y = 2;
inline void PointB::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PointB::y() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.PointB.y)
  return _internal_y();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PointB::set_y(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.y_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.PointB.y)
}
inline ::std::string* PROTOBUF_NONNULL PointB::mutable_y()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_y();
  // @@protoc_insertion_point(field_mutable:cot.PointB.y)
  return _s;
}
inline const ::std::string& PointB::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_.Get();
}
inline void PointB::_internal_set_y(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PointB::_internal_mutable_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.y_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PointB::release_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.PointB.y)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.y_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.y_.Set("", GetArena());
  }
  return released;
}
inline void PointB::set_allocated_y(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.y_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.y_.IsDefault()) {
    _impl_.y_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.PointB.y)
}

// -------------------------------------------------------------------

// EncryptedPayloads

// bytes e0 = 1;
inline void EncryptedPayloads::clear_e0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.e0_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& EncryptedPayloads::e0() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.EncryptedPayloads.e0)
  return _internal_e0();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EncryptedPayloads::set_e0(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.e0_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.EncryptedPayloads.e0)
}
inline ::std::string* PROTOBUF_NONNULL EncryptedPayloads::mutable_e0()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_e0();
  // @@protoc_insertion_point(field_mutable:cot.EncryptedPayloads.e0)
  return _s;
}
inline const ::std::string& EncryptedPayloads::_internal_e0() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.e0_.Get();
}
inline void EncryptedPayloads::_internal_set_e0(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.e0_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EncryptedPayloads::_internal_mutable_e0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.e0_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EncryptedPayloads::release_e0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.EncryptedPayloads.e0)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.e0_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.e0_.Set("", GetArena());
  }
  return released;
}
inline void EncryptedPayloads::set_allocated_e0(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.e0_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.e0_.IsDefault()) {
    _impl_.e0_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.EncryptedPayloads.e0)
}

// bytes e1 = 2;
inline void EncryptedPayloads::clear_e1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.e1_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& EncryptedPayloads::e1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cot.EncryptedPayloads.e1)
  return _internal_e1();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EncryptedPayloads::set_e1(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.e1_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cot.EncryptedPayloads.e1)
}
inline ::std::string* PROTOBUF_NONNULL EncryptedPayloads::mutable_e1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_e1();
  // @@protoc_insertion_point(field_mutable:cot.EncryptedPayloads.e1)
  return _s;
}
inline const ::std::string& EncryptedPayloads::_internal_e1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.e1_.Get();
}
inline void EncryptedPayloads::_internal_set_e1(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.e1_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EncryptedPayloads::_internal_mutable_e1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.e1_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EncryptedPayloads::release_e1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cot.EncryptedPayloads.e1)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.e1_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.e1_.Set("", GetArena());
  }
  return released;
}
inline void EncryptedPayloads::set_allocated_e1(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.e1_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.e1_.IsDefault()) {
    _impl_.e1_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:cot.EncryptedPayloads.e1)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cot


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // cot_2eproto_2epb_2eh
