// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cot.proto
// Protobuf C++ Version: 7.34.1

#include "cot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cot {

inline constexpr PointB::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        y_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PointB::PointB(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PointB_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct PointBDefaultTypeInternal {
  constexpr PointBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointBDefaultTypeInternal() {}
  union {
    PointB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointBDefaultTypeInternal _PointB_default_instance_;

inline constexpr PointA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        y_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PointA::PointA(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PointA_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct PointADefaultTypeInternal {
  constexpr PointADefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointADefaultTypeInternal() {}
  union {
    PointA _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointADefaultTypeInternal _PointA_default_instance_;

inline constexpr EncryptedPayloads::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        e0_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        e1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr EncryptedPayloads::EncryptedPayloads(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EncryptedPayloads_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct EncryptedPayloadsDefaultTypeInternal {
  constexpr EncryptedPayloadsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EncryptedPayloadsDefaultTypeInternal() {}
  union {
    EncryptedPayloads _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EncryptedPayloadsDefaultTypeInternal _EncryptedPayloads_default_instance_;
}  // namespace cot
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_cot_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_cot_2eproto = nullptr;
const ::uint32_t
    TableStruct_cot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cot::PointA, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cot::PointA, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::cot::PointA, _impl_.y_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cot::PointB, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cot::PointB, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::cot::PointB, _impl_.y_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::cot::EncryptedPayloads, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::cot::EncryptedPayloads, _impl_.e0_),
        PROTOBUF_FIELD_OFFSET(::cot::EncryptedPayloads, _impl_.e1_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::cot::PointA)},
        {7, sizeof(::cot::PointB)},
        {14, sizeof(::cot::EncryptedPayloads)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::cot::_PointA_default_instance_._instance,
    &::cot::_PointB_default_instance_._instance,
    &::cot::_EncryptedPayloads_default_instance_._instance,
};
const char descriptor_table_protodef_cot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tcot.proto\022\003cot\"\036\n\006PointA\022\t\n\001x\030\001 \001(\014\022\t\n"
    "\001y\030\002 \001(\014\"\036\n\006PointB\022\t\n\001x\030\001 \001(\014\022\t\n\001y\030\002 \001(\014"
    "\"+\n\021EncryptedPayloads\022\n\n\002e0\030\001 \001(\014\022\n\n\002e1\030"
    "\002 \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_cot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cot_2eproto = {
    false,
    false,
    133,
    descriptor_table_protodef_cot_2eproto,
    "cot.proto",
    &descriptor_table_cot_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_cot_2eproto::offsets,
    file_level_enum_descriptors_cot_2eproto,
    file_level_service_descriptors_cot_2eproto,
};
namespace cot {
// ===================================================================

class PointA::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PointA>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PointA, _impl_._has_bits_);
};

PointA::PointA(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cot.PointA)
}
PROTOBUF_NDEBUG_INLINE PointA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::cot::PointA& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        x_(arena, from.x_),
        y_(arena, from.y_) {}

PointA::PointA(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PointA& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointA_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PointA* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cot.PointA)
}
PROTOBUF_NDEBUG_INLINE PointA::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        x_(arena),
        y_(arena) {}

inline void PointA::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PointA::~PointA() {
  // @@protoc_insertion_point(destructor:cot.PointA)
  SharedDtor(*this);
}
inline void PointA::SharedDtor(MessageLite& self) {
  PointA& this_ = static_cast<PointA&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.x_.Destroy();
  this_._impl_.y_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PointA::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PointA(arena);
}
constexpr auto PointA::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PointA),
                                            alignof(PointA));
}
constexpr auto PointA::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PointA_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &PointA::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PointA>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PointA::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PointA>(), &PointA::ByteSizeLong,
              &PointA::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PointA, _impl_._cached_size_),
          false,
      },
      &PointA::kDescriptorMethods,
      &descriptor_table_cot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PointA_class_data_ =
        PointA::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PointA::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PointA_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PointA_class_data_.tc_table);
  return PointA_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
PointA::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PointA, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PointA_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cot::PointA>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes y = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PointA, _impl_.y_)}},
    // bytes x = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PointA, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes x = 1;
    {PROTOBUF_FIELD_OFFSET(PointA, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes y = 2;
    {PROTOBUF_FIELD_OFFSET(PointA, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PointA::Clear() {
// @@protoc_insertion_point(message_clear_start:cot.PointA)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.x_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.y_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PointA::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PointA& this_ = static_cast<const PointA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PointA::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PointA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cot.PointA)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_x().empty()) {
      const ::std::string& _s = this_._internal_x();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_y().empty()) {
      const ::std::string& _s = this_._internal_y();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cot.PointA)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PointA::ByteSizeLong(const MessageLite& base) {
  const PointA& this_ = static_cast<const PointA&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PointA::ByteSizeLong() const {
  const PointA& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cot.PointA)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_x().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_x());
      }
    }
    // bytes y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_y().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_y());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PointA::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PointA*>(&to_msg);
  auto& from = static_cast<const PointA&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cot.PointA)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_x().empty()) {
        _this->_internal_set_x(from._internal_x());
      } else {
        if (_this->_impl_.x_.IsDefault()) {
          _this->_internal_set_x("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_y().empty()) {
        _this->_internal_set_y(from._internal_y());
      } else {
        if (_this->_impl_.y_.IsDefault()) {
          _this->_internal_set_y("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PointA::CopyFrom(const PointA& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cot.PointA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PointA::InternalSwap(PointA* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.x_, &other->_impl_.x_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.y_, &other->_impl_.y_, arena);
}

::google::protobuf::Metadata PointA::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PointB::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PointB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PointB, _impl_._has_bits_);
};

PointB::PointB(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointB_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cot.PointB)
}
PROTOBUF_NDEBUG_INLINE PointB::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::cot::PointB& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        x_(arena, from.x_),
        y_(arena, from.y_) {}

PointB::PointB(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PointB& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointB_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PointB* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cot.PointB)
}
PROTOBUF_NDEBUG_INLINE PointB::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        x_(arena),
        y_(arena) {}

inline void PointB::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PointB::~PointB() {
  // @@protoc_insertion_point(destructor:cot.PointB)
  SharedDtor(*this);
}
inline void PointB::SharedDtor(MessageLite& self) {
  PointB& this_ = static_cast<PointB&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.x_.Destroy();
  this_._impl_.y_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PointB::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PointB(arena);
}
constexpr auto PointB::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PointB),
                                            alignof(PointB));
}
constexpr auto PointB::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PointB_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &PointB::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PointB>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PointB::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PointB>(), &PointB::ByteSizeLong,
              &PointB::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PointB, _impl_._cached_size_),
          false,
      },
      &PointB::kDescriptorMethods,
      &descriptor_table_cot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PointB_class_data_ =
        PointB::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PointB::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PointB_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PointB_class_data_.tc_table);
  return PointB_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
PointB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PointB, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PointB_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cot::PointB>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes y = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PointB, _impl_.y_)}},
    // bytes x = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PointB, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes x = 1;
    {PROTOBUF_FIELD_OFFSET(PointB, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes y = 2;
    {PROTOBUF_FIELD_OFFSET(PointB, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PointB::Clear() {
// @@protoc_insertion_point(message_clear_start:cot.PointB)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.x_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.y_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PointB::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PointB& this_ = static_cast<const PointB&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PointB::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PointB& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cot.PointB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_x().empty()) {
      const ::std::string& _s = this_._internal_x();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_y().empty()) {
      const ::std::string& _s = this_._internal_y();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cot.PointB)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PointB::ByteSizeLong(const MessageLite& base) {
  const PointB& this_ = static_cast<const PointB&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PointB::ByteSizeLong() const {
  const PointB& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cot.PointB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_x().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_x());
      }
    }
    // bytes y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_y().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_y());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PointB::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PointB*>(&to_msg);
  auto& from = static_cast<const PointB&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cot.PointB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_x().empty()) {
        _this->_internal_set_x(from._internal_x());
      } else {
        if (_this->_impl_.x_.IsDefault()) {
          _this->_internal_set_x("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_y().empty()) {
        _this->_internal_set_y(from._internal_y());
      } else {
        if (_this->_impl_.y_.IsDefault()) {
          _this->_internal_set_y("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PointB::CopyFrom(const PointB& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cot.PointB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PointB::InternalSwap(PointB* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.x_, &other->_impl_.x_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.y_, &other->_impl_.y_, arena);
}

::google::protobuf::Metadata PointB::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EncryptedPayloads::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EncryptedPayloads>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_._has_bits_);
};

EncryptedPayloads::EncryptedPayloads(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EncryptedPayloads_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cot.EncryptedPayloads)
}
PROTOBUF_NDEBUG_INLINE EncryptedPayloads::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::cot::EncryptedPayloads& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        e0_(arena, from.e0_),
        e1_(arena, from.e1_) {}

EncryptedPayloads::EncryptedPayloads(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EncryptedPayloads& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EncryptedPayloads_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EncryptedPayloads* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cot.EncryptedPayloads)
}
PROTOBUF_NDEBUG_INLINE EncryptedPayloads::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        e0_(arena),
        e1_(arena) {}

inline void EncryptedPayloads::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EncryptedPayloads::~EncryptedPayloads() {
  // @@protoc_insertion_point(destructor:cot.EncryptedPayloads)
  SharedDtor(*this);
}
inline void EncryptedPayloads::SharedDtor(MessageLite& self) {
  EncryptedPayloads& this_ = static_cast<EncryptedPayloads&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.e0_.Destroy();
  this_._impl_.e1_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EncryptedPayloads::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EncryptedPayloads(arena);
}
constexpr auto EncryptedPayloads::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EncryptedPayloads),
                                            alignof(EncryptedPayloads));
}
constexpr auto EncryptedPayloads::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EncryptedPayloads_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &EncryptedPayloads::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EncryptedPayloads>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EncryptedPayloads::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EncryptedPayloads>(), &EncryptedPayloads::ByteSizeLong,
              &EncryptedPayloads::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_._cached_size_),
          false,
      },
      &EncryptedPayloads::kDescriptorMethods,
      &descriptor_table_cot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EncryptedPayloads_class_data_ =
        EncryptedPayloads::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EncryptedPayloads::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EncryptedPayloads_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EncryptedPayloads_class_data_.tc_table);
  return EncryptedPayloads_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
EncryptedPayloads::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EncryptedPayloads_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cot::EncryptedPayloads>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes e1 = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_.e1_)}},
    // bytes e0 = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_.e0_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes e0 = 1;
    {PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_.e0_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes e1 = 2;
    {PROTOBUF_FIELD_OFFSET(EncryptedPayloads, _impl_.e1_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EncryptedPayloads::Clear() {
// @@protoc_insertion_point(message_clear_start:cot.EncryptedPayloads)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.e0_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.e1_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EncryptedPayloads::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EncryptedPayloads& this_ = static_cast<const EncryptedPayloads&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EncryptedPayloads::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EncryptedPayloads& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:cot.EncryptedPayloads)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes e0 = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_e0().empty()) {
      const ::std::string& _s = this_._internal_e0();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // bytes e1 = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_e1().empty()) {
      const ::std::string& _s = this_._internal_e1();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cot.EncryptedPayloads)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EncryptedPayloads::ByteSizeLong(const MessageLite& base) {
  const EncryptedPayloads& this_ = static_cast<const EncryptedPayloads&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EncryptedPayloads::ByteSizeLong() const {
  const EncryptedPayloads& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cot.EncryptedPayloads)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes e0 = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_e0().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_e0());
      }
    }
    // bytes e1 = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_e1().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_e1());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EncryptedPayloads::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EncryptedPayloads*>(&to_msg);
  auto& from = static_cast<const EncryptedPayloads&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:cot.EncryptedPayloads)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_e0().empty()) {
        _this->_internal_set_e0(from._internal_e0());
      } else {
        if (_this->_impl_.e0_.IsDefault()) {
          _this->_internal_set_e0("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_e1().empty()) {
        _this->_internal_set_e1(from._internal_e1());
      } else {
        if (_this->_impl_.e1_.IsDefault()) {
          _this->_internal_set_e1("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EncryptedPayloads::CopyFrom(const EncryptedPayloads& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:cot.EncryptedPayloads)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EncryptedPayloads::InternalSwap(EncryptedPayloads* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.e0_, &other->_impl_.e0_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.e1_, &other->_impl_.e1_, arena);
}

::google::protobuf::Metadata EncryptedPayloads::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
